### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by habuenav** [andykarpov/karabas-go-pcb-dream-addon#1]
Hello, this pcb is great, although my intention is to use it for another purpose, I visited your YouTube channel to see if you had any video showing the module in operation, I would like to know how it works? Would it be possible for you to upload a video using it? Thanks in advance and congratulations.

**Comment by andykarpov** [comment]
I suggest to see how it works in the following youtube short: https://www.youtube.com/shorts/w2a821dsFIs

**Comment by habuenav** [comment]
Thanks for answering.
Wow, it sounds incredible, I already had the pcbs made and ordered the sam2695, I'm waiting for it to arrive to try it. I ask you, do you have or know of any pcb with a size and performance similar to yours but that uses the vs1053 ic, something like this? https://blog.naver.com/mk1017sh/222591897060 or this other one
https://wiki.ruilongmaker.cc/index.php?title=%E6%96%87%E4%BB%B6:RLSEB153VS-01.jpg

**Comment by andykarpov** [comment]
As far as I know, the VS1053 requires a bit more passive components to run. 
Please see the board from SparkFun and it's arduino examples: https://www.sparkfun.com/products/retired/9943
